from web.forms import DataForm
from web.forms import SqrtForm
from web.forms import FromFileForm
from web.forms import SquareFuncForm
from web.forms import MatplotlibOptionsForm
from web.forms import SeabornOptionsForm
from web.forms import BokehOptionsForm
from web.forms import PlotlyOptionsForm
from web.forms import PygalOptionsForm
